from . import product
from . import stock_move
from . import stock_move_line
from . import stock_lot
from . import purchase_order
from . import product_packaging
from . import stock_picking
from . import mrp_production
from . import product_category
from . import stock_scrap
from . import stock_location
from . import stock_picking_type
from . import stock_quant_package
from . import mrp_production_batch
from . import stock_quant
from . import product_packaging_type
from . import stock_rule
from . import farm
from . import fleet