{
    'name': "Frozentrade Meta Package",
    'depends': [
        'po_from_ship',
        'mrp_production_batch',
        'delivery',
        #'stock_barcode',
        'stock_exception',
        'stock_push_on_done',
        'product_expiry',
        'quality_control',
        # 'delivery_total_weight_from_packaging',
        # 'stock_packaging_calculator',
        # 'stock_product_qty_by_packaging',
        # 'stock_split_picking'
    ],
    'data': [
        'views/stock_move_views.xml',
        'views/product_category.xml',
        'views/mrp_production.xml',
        'views/stock_location.xml',
        'views/stock_picking_type.xml',
        'views/stock_picking.xml',
        'views/product_packaging_type.xml',
        'views/mrp_production_batch.xml',
        'views/stock_move_line.xml',
        'views/stock_quant_package.xml',
        # 'views/farm.xml',
        # 'views/fleet.xml',
        # 'security/ir.model.access.csv',
        'security/stock_security.xml',
        'reports/account_invoice_inherited.xml',
        'reports/paperformat_portrait.xml',
        'reports/report_packing_list.xml',
        'reports/report_fiche_palette_expedition.xml',
        'reports/report_package_barcode.xml',
        'reports/report_vgm_certification.xml',
        'reports/report_etablissement_connaissement.xml',
        'reports/report_picking.xml',
        'wizard/quality_check_wizard.xml',
    ],
}
