# -*- coding: utf-8 -*-
{
    'name': "BADEP Modules selection",

    'summary': """Add some base modules to any installation""",

    'description': """
    """,

    'author': "BADEP",
    'website': "https://badep.ma",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Technical Settings',
    'version': '16.0.1',

    # any module necessary for this one to work correctly
    'depends': [
        'auditlog',
        # 'base_attachment_optimize',
        # 'base_action_xmlrpc',
        # 'base_action_boto3',
        # 'base_action_requests',
        'base_automation',
        # 'base_custom_info',
        'base_cron_exclusion',
        # 'base_conditional_image',
        # 'base_export_manager',
        'base_fontawesome',
        'base_geolocalize',
        # 'base_import_match',
        # 'base_name_search_improved',
        'base_optional_quick_create',
        # 'base_partner_merge_extended',
        # 'base_phone',
        # 'base_report_auto_create_qweb',
        # 'base_search_custom_field_filter',
        # 'base_search_fuzzy',
        # 'base_search_mail_content',
        'base_technical_features',
        # 'bi_sql_editor',
        # 'bi_view_editor',
        'calendar',
        'database_cleanup',
        # 'datetime_formatter',
        # 'document',
        # 'excel_import_export',
        # 'html_image_url_extractor',
        # 'ks_list_view_manager',
        'mail_activity_board',
        # 'mail_activity_creator',
        # 'mail_activity_done',
        # 'mail_activity_partner',
        # 'mail_all',
        # 'mail_archives',
        'mail_attach_existing_attachment',
        # 'mail_autosubscribe',
        # 'mail_full_expand',
        # 'mail_inline_css',
        # 'mail_layout_preview',
        # 'mail_notification_custom_subject',
        # 'mail_notify',
        'mail_optional_autofollow',
        # 'mail_optional_follower_notification',
        # 'mail_private',
        # 'mail_to',
        # 'mail_restrict_follower_selection',
        # 'mail_sc hedule',
        'mail_tracking',
        'mail_smtp_per_user',
        # 'mail_user_alias',
        # 'mass_editing',
        # 'mobile_android',
        'module_auto_update',
        'partner_vat_unique',
        'phone_validation',
        'portal',
        # 'scheduler_error_mailer',
        # 'sequence_reset_period',
        # 'slow_statement_logger',
        'sql_export_mail',
        # 'sql_export_excel',
        'web_advanced_search',
        # 'web_chatter_position',
        # 'web_decimal_numpad_dot',
        # 'web_dialog_size',
        # 'web_drop_target',
        # 'web_edit_user_filter',
        # 'web_editor_background_color',
        # 'web_export_view',
        # 'web_favicon',
        # 'web_group_by_percentage',
        # 'web_listview_range_select',
        # 'web_m2x_options',
        # 'web_pwa_oca',
        'web_refresher',
        'web_search_with_and',
        'web_sheet_full_width',
        # 'web_tree_dynamic_colored_field',
        # 'web_tree_image_tooltip',
        # 'web_tree_many2one_clickable',
        # 'web_widget_image_download',
        # 'web_widget_color',
        # 'web_widget_digitized_signature',
        # 'web_widget_domain_editor_dialog',
        # 'web_widget_image_url',
        # 'web_widget_many2many_tags_multi_selection',
        # 'web_widget_numeric_step',
        # 'web_widget_x2many_2d_matrix',
    ],

    'installable': True,
    'auto_install': True,
    'application': True
}
